### ISSUE TITLE
No data in Genus-summary.tsv

### ISSUE THREAD

**Issue by mishkb** [mikaells/RibDif#4]
Hi @mikaells 

I'm running RibDif on WSL2 Ubuntu 18.04 looking at Pseudomonas. Everything seems to have run well, heatmaps and overlap-summary files all generated etc. But I get no data in the genus-summary.tsv file - besides a list of the >900 genomes, there are only '0' in the #16S, Mean, SD, Max etc columns (see attached, changed to .txt to allow upload here).

[Pseudomonas-summary.txt](https://github.com/mikaells/RibDif/files/8092936/Pseudomonas-summary.txt)

Here is the command I ran: 

`RibDif.sh --genus Pseudomonas --primers /home/michb/RibDif/16SONT_plus.primers --clobber false --ANI false --frag false --msa false --id 1 --threads 8`

Any ideas of what has happened?  I have run RibDif with other genera and with other primer sets and get the same apparently "empty" genus-summary.tsv file.

Michelle

**Comment by mikaells** [comment]
Hi Michelle,

Just add the --ANI flag, it will run the detailed intragenomic analyses and fill out the sheet. It takes quite a while (especially for something as big as pseudomonas) and is disabled by default.

I should probably write that in more detail somewhere. Also, I guess i could technically fish out #16S without the --ANI analysis, I'll have a look at that.

**Comment by mishkb** [comment]
Thanks for the info on the --ANI flag. I'll try it on a smaller genus first 🙂
